In [ ]:
#around function - rounding
import numpy as np  
arr = np.array([20.8999,67.89899,54.63409])  
print(np.around(arr,1))

In [ ]:
#floor function - integer value of number
import numpy as np  
arr = np.array([20.8,67.99,54.09])  
print(np.floor(arr))

In [ ]:
#ceil function - integer value +1
import numpy as np  
arr = np.array([20.8,67.99,54.09])  
print(np.ceil(arr))

In [ ]:
#Arithmetic operations
import numpy as np
 
a = np.array([1, 2, 3, 4])
 
# add 5 to every element
print ( a+5)
 
# subtract 2 from each element
print ( a-2)
 
# multiply each element by 5 
print (a*10)
 
# divide each element by 2
print ( a/2)

In [2]:
#Slicing
import numpy as np
arr=([1,2,5,6,7])
print(arr[1])
arr[2:5]

2


[5, 6, 7]

In [3]:
#unary operations
arr = np.array([[1,5, 12],
                [2,32, 20],
                [3, 40, 13]])
 
 
print(arr.max(axis = 1))  # using columns
 
print (arr.min(axis = 0))   #using rows
 
print ( arr.sum())

[12 32 40]
[ 1  5 12]
128


In [9]:
#binary operations
import numpy as np
 
a = np.array([[1, 2],
            [3, 4]])
b = np.array([[4, 3],
            [2, 1]])
 
print (a + b)
print (a*b)
print (np.around(a/b,2))

[[5 5]
 [5 5]]
[[4 6]
 [6 4]]
[[0.25 0.67]
 [1.5  4.  ]]


In [ ]:
1. Write a Python program to convert a list and tuple into Numpy arrays.

List to array: [1 2 3 4 5 6 7 8] 
Tuple to array:
[[8 4 6]  [1 2 3]]

Discuss how the list and tuple differ from the arrays.

2. Write a Python program to append values to the end of a Numpy array. 

Expected Output:
Original array:
 [10, 20, 30] 
After append values to the end of the array:
[10 20 30 40 50 60 70 80 90]
NUMPY Arrays

